name: default
metrics:
  - metric: '\# Roots'
    optimization: min
    weight: 1
  - metric: '\# New Terms'
    optimization: min
    weight: 1
  - metric: 'Missing'
    optimization: min
    weight: 1
  - metric: '\# Self Loops'
    optimization: min
    weight: 1
#  - metric: '\# Parents'
#    optimization: min
#    weight: 1
  - metric: '\# Children'
    optimization: max
    weight: 1
  - metric: '\# Edges'
    optimization: min
    weight: 1
#  - metric: '\# Bridges'
#    optimization: min
#    weight: 1